Traceback (most recent call last):
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\acer\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\acer\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import psycopg2

pg_conn = psycopg2.connect(
    dbname="defaultdb",
    user="avnadmin",
    password="AVNS_Cq_rz3j4QTiiunKJ08p",
    host="pg-17afc059-aqbilbaraka.d.aivencloud.com",
    port="16932"
)

query_pg = "SELECT * FROM public.irispostgresql"
data_pg = pd.read_sql(query_pg, pg_conn)

data_pg
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mOperationalError[0m                          Traceback (most recent call last)
Cell [1;32mIn[2], line 4[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpandas[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mpd[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mpsycopg2[39;00m
[1;32m----> 4[0m pg_conn [38;5;241m=[39m [43mpsycopg2[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m
[0;32m      5[0m [43m    [49m[43mdbname[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mdefaultdb[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m      6[0m [43m    [49m[43muser[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mavnadmin[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m      7[0m [43m    [49m[43mpassword[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mAVNS_Cq_rz3j4QTiiunKJ08p[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m      8[0m [43m    [49m[43mhost[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mpg-17afc059-aqbilbaraka.d.aivencloud.com[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m      9[0m [43m    [49m[43mport[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m16932[39;49m[38;5;124;43m"[39;49m
[0;32m     10[0m [43m)[49m
[0;32m     12[0m query_pg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mSELECT * FROM public.irispostgresql[39m[38;5;124m"[39m
[0;32m     13[0m data_pg [38;5;241m=[39m pd[38;5;241m.[39mread_sql(query_pg, pg_conn)

File [1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\psycopg2\__init__.py:122[0m, in [0;36mconnect[1;34m(dsn, connection_factory, cursor_factory, **kwargs)[0m
[0;32m    119[0m     kwasync[[38;5;124m'[39m[38;5;124masync_[39m[38;5;124m'[39m] [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m'[39m[38;5;124masync_[39m[38;5;124m'[39m)
[0;32m    121[0m dsn [38;5;241m=[39m _ext[38;5;241m.[39mmake_dsn(dsn, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m--> 122[0m conn [38;5;241m=[39m _connect(dsn, connection_factory[38;5;241m=[39mconnection_factory, [38;5;241m*[39m[38;5;241m*[39mkwasync)
[0;32m    123[0m [38;5;28;01mif[39;00m cursor_factory [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m    124[0m     conn[38;5;241m.[39mcursor_factory [38;5;241m=[39m cursor_factory

[1;31mOperationalError[0m: connection to server at "pg-17afc059-aqbilbaraka.d.aivencloud.com" (165.22.59.166), port 16932 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?


